#Recuperar peliculas
https://upgradedumbrella-pnba--1234--7dbe22a9.local-corp.webcontainer.io/movies

#Recuperar peliculas por ID
https://upgradedumbrella-pnba--1234--7dbe22a9.local-corp.webcontainer.io/movies/1

#Recuperar peliculas por género
https://upgradedumbrella-pnba--1234--7dbe22a9.local-corp.webcontainer.io/movies?genre=terror